spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.application.name=orderflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# MongoDB Configuration (Spring Boot 4.x uses spring.mongodb.* prefix)
spring.mongodb.uri=mongodb://${DB_USERNAME}:${DB_PASSWORD}@localhost:27017/orderflow?authSource=admin